//
//  StructCardJB.swift
//  ProjetGoodTrips
//
//  Created by apprenant79 on 28/01/2025.
//

import Foundation

struct cardJB: Identifiable{
    var id=UUID()
    var photo: String
    var title: String
    var description: String
    var description_detail: String
    var likeIcon:String = "heart.fill"
    var likeNb: Int
    var comIcon:String = "bubble.fill"
    var comNb: Int
    var favourite: Bool = false
}

var cardNews:[cardJB] = [cardJB(photo: "Tokyo", title: "🏙️ Tokyo", description: "Une métropole où la tradition rencontre la modernité, offrant une expérience culturelle unique.", description_detail:"Dès mon arrivée à Tokyo, j’ai été frappé par l’énergie de la ville. En me promenant dans Shibuya, j’ai traversé l’un des passages piétons les plus fréquentés du monde avant de grimper au sommet du Shibuya Sky pour une vue imprenable sur les lumières de la capitale. Puis, changement d’ambiance : dans les ruelles du quartier d’Asakusa, le temple Senso-ji se dressait majestueusement, baigné par l’odeur des bâtons d’encens. J’ai goûté des taiyaki encore chauds, puis pris un train jusqu’à Akihabara, où les écrans géants et les magasins de mangas m’ont transporté dans un univers futuriste. Tokyo est une ville où chaque rue raconte une histoire différente.", likeNb: 3592, comNb: 290),
                         cardJB(photo: "NewYork", title: "🗽 New York", description: "La ville qui ne dort jamais, entre gratte-ciels vertigineux, avenues mythiques et énergie débordante.", description_detail:"À peine sorti du métro, j’ai été happé par l’énergie de Manhattan. J’ai commencé ma journée à Central Park, où le contraste entre la verdure et les gratte-ciels était saisissant. Puis, j’ai flâné sur la Cinquième Avenue avant de grimper au sommet du Top of the Rock : la vue sur l’Empire State Building et la skyline de la ville était à couper le souffle.À midi, direction un deli typiquement new-yorkais pour un pastrami sandwich légendaire. L’après-midi, j’ai pris le ferry vers la Statue de la Liberté et Ellis Island, où des millions d’immigrants avaient autrefois posé le pied en quête d’un nouveau départ.Le soir, j’ai assisté à un match des Knicks au Madison Square Garden avant de terminer ma journée sur un rooftop à Brooklyn, un cocktail à la main, face à la skyline illuminée. New York est une ville qui vibre, fascine et ne cesse jamais de surprendre.", likeNb: 3562, comNb: 290),
                         cardJB(photo: "Londres2", title: "🇬🇧 Londres", description: "Une ville vibrante mêlant histoire royale, culture contemporaine et quartiers éclectiques.", description_detail:"Dès mon arrivée, j’ai emprunté un mythique bus rouge à deux étages pour traverser Westminster. Big Ben, imposant, résonnait dans l’air brumeux du matin. Après une balade le long de la Tamise, j’ai exploré le marché de Borough, un paradis pour les amateurs de street food : j’y ai goûté un fish and chips croustillant et une tarte au bœuf et à la Guinness. L’après-midi, direction Notting Hill, où les façades pastel et les petites librairies semblaient sorties d’un film. Puis, changement d’ambiance à Camden Town, avec ses boutiques underground et son marché alternatif. Le soir, j’ai assisté à une comédie musicale dans le West End, suivi d’un cocktail dans un speakeasy caché sous une vieille librairie. Londres est un mélange d’élégance, d’excentricité et d’inspiration constante.", likeNb: 3592, comNb: 290),
                         cardJB(photo: "Chili", title: "🏞️ Valparaíso", description: "Une ville côtière colorée réputée pour son art de rue vibrant et ses collines pittoresques.", description_detail: "Dès mon arrivée à Valparaíso, j’ai su que cette ville avait une âme unique. Les façades des maisons, peintes dans un kaléidoscope de couleurs vives, se dressaient sur les collines escarpées, entrelacées par un dédale d’escaliers et de funiculaires grinçants. J’ai passé ma matinée à flâner dans le quartier de Cerro Alegre, admirant les fresques murales qui racontaient mille histoires à travers des explosions de couleurs. Plus tard, attablé à une terrasse surplombant l’océan, j’ai dégusté une empanada de mariscos en écoutant un musicien de rue jouer une mélodie entraînante. L’air salin, le vent léger et la vue sur la baie donnaient un sentiment de liberté absolue. En fin de journée, je suis monté jusqu’à La Sebastiana, l’ancienne maison de Pablo Neruda. Depuis sa fenêtre, j’ai contemplé Valparaíso s’illuminer lentement, les lumières scintillant comme des étoiles tombées sur la terre.", likeNb: 2800, comNb: 220),
                         cardJB(photo: "Tbilissi", title: "🏰 Tbilissi", description: "Une capitale européenne émergente mêlant architecture ancienne et vie nocturne dynamique.", description_detail:"Dès mon arrivée, je me suis laissé envoûter par l’atmosphère unique de Tbilissi. Après avoir grimpé jusqu’à la forteresse de Narikala, j’ai contemplé la vue panoramique sur la ville, entre minarets, clochers et immeubles contemporains. Ensuite, j’ai arpenté les ruelles de la vieille ville, où les façades colorées et les balcons fleuris donnaient un charme suranné au quartier. L’après-midi, je me suis rendu aux célèbres bains soufrés d’Abanotubani, où l’eau chaude et minérale m’a enveloppé dans une détente absolue. Le soir, je me suis attablé dans une petite taverne, goûtant à un vin géorgien millénaire tout en écoutant une mélodie jouée au pandouri. Tbilissi est une ville où le temps semble suspendu entre traditions et modernité.", likeNb: 3200, comNb: 250),
                         cardJB(photo: "Laos", title: "🏝️ Luang Prabang", description: "Une ville paisible inscrite au patrimoine mondial de l'UNESCO, célèbre pour ses temples bouddhistes et ses paysages naturels.", description_detail:"À l’aube, j’ai assisté au rituel silencieux de l’aumône des moines, une procession empreinte de spiritualité. Ensuite, j’ai exploré les ruelles bordées de maisons en bois et de cafés paisibles où l’arôme du café laotien flottait dans l’air. L’après-midi, après une balade en bateau sur le Mékong, je suis arrivé aux chutes de Kuang Si. L’eau turquoise formait des bassins naturels dans lesquels j’ai plongé avec bonheur. Le soir, en flânant sur le marché nocturne, j’ai goûté des brochettes de viande grillée et des sticky rice au lait de coco. Luang Prabang est une ville où chaque instant semble inviter à la contemplation.", likeNb: 2900, comNb: 230),
                         cardJB(photo: "Oman", title: "🏜️ Oman", description: "Un pays du Moyen-Orient offrant des paysages désertiques époustouflants, des plages immaculées et une riche histoire.", description_detail:"Mon voyage a commencé à Mascate, où j’ai visité la majestueuse mosquée du Sultan Qaboos, son immense tapis persan et son lustre en cristal reflétant la lumière dorée. Puis, direction le désert de Wahiba Sands : après une traversée en 4x4, j’ai gravi une dune pour observer le soleil disparaître dans une mer de sable doré. Le lendemain, j’ai exploré Wadi Shab, une oasis aux eaux émeraude cachée entre des falaises abruptes. Après une courte randonnée, j’ai nagé dans des piscines naturelles menant à une grotte secrète illuminée par la lumière du jour. Le soir, sous une tente bédouine, j’ai siroté un thé à la cardamome en écoutant le silence du désert. Oman est une terre d’évasion et d’authenticité.", likeNb: 3100, comNb: 240),
                         cardJB(photo: "Mexique", title: "🏖️ Mérida", description: "Une ville coloniale vibrante connue pour sa culture maya, sa cuisine savoureuse et ses festivals colorés.", description_detail:"Dès mon arrivée sur la Plaza Grande, j’ai été enveloppé par l’animation de Mérida. Entre les musiciens de rue et les vendeurs d’elotes (épis de maïs grillés), l’énergie de la ville était palpable. J’ai visité la cathédrale San Ildefonso, un monument impressionnant chargé d’histoire, avant de me perdre dans les ruelles colorées du centre. Le lendemain, j’ai roulé jusqu’au site maya d’Uxmal. Contrairement à Chichén Itzá, ici, le calme régnait. J’ai gravi la Pyramide du Devin et admiré la jungle s’étendre à l’infini. Sur le chemin du retour, une baignade dans un cénote caché, entouré de lianes et de formations rocheuses, a été une expérience inoubliable. Le soir, sous un ciel étoilé, j’ai goûté une cochinita pibil, un plat traditionnel à base de porc mariné, en me laissant bercer par la musique mariachi. Mérida est un voyage au cœur de l’âme mexicaine.", likeNb: 2700, comNb: 210),
                         cardJB(photo: "Canada", title: "🇨🇦 Banff", description: "Un paradis naturel avec des lacs turquoise et des montagnes majestueuses, idéal pour les amoureux de la nature.", description_detail: "J’ai pris la route à l’aube, quittant Banff pour explorer le lac Moraine. À mon arrivée, le soleil commençait à percer les sommets enneigés, donnant à l’eau une teinte bleue irréelle. Assis sur un rocher, j’ai simplement savouré le silence et l’immensité du paysage. Plus tard, j’ai emprunté un sentier menant aux chutes de Johnston Canyon, où l’eau glacée dévalait les parois rocheuses. Le soir, autour d’un feu de camp, sous un ciel illuminé par la Voie lactée, j’ai compris pourquoi Banff est l’un des plus beaux endroits sur Terre.", likeNb: 2100, comNb: 119),
                         cardJB(photo: "Indonésie", title: "🇮🇩 Gili Islands", description: "Des îles paradisiaques aux eaux cristallines, parfaites pour la plongée et la détente.", description_detail: "Dès que j’ai posé le pied sur Gili Air, j’ai su que j’étais arrivé au paradis. Pas de voitures, juste le bruit des vagues et le cliquetis des vélos sur les chemins de sable. J’ai enfilé mon masque et plongé dans une eau translucide, où j’ai nagé aux côtés de tortues majestueuses glissant avec grâce dans les courants marins. À la tombée de la nuit, allongé sur un hamac face à l’océan, j’ai regardé les lanternes flotter dans le ciel, un cocktail de fruits frais à la main. Gili, c’est l’évasion absolue.", likeNb: 1286, comNb: 45),
                         cardJB(photo: "Italie", title: "🍕 Matera", description: "Une ville historique avec des habitations troglodytes uniques et une riche histoire culturelle.", description_detail: "Me perdre dans les ruelles de Matera, c’était comme marcher dans un décor de film. Sous la lumière dorée du coucher de soleil, les Sassi – ces habitations creusées dans la roche – ressemblaient à un village suspendu dans le temps. Je suis entré dans une vieille trattoria nichée au cœur des grottes, où j’ai dégusté des pâtes faites maison avec une sauce aux cèpes et à la truffe. Le soir, depuis la terrasse de mon logement troglodyte, j’ai observé la ville s’illuminer peu à peu, offrant un spectacle magique et intemporel.", likeNb: 3490, comNb: 190),
                         cardJB(photo: "Vietnam", title: "🇻🇳 Sapa", description: "Des rizières en terrasses spectaculaires et une immersion dans les cultures ethniques montagnardes.", description_detail: "Le brouillard flottait encore sur les collines lorsque j’ai quitté mon auberge pour une randonnée à travers les rizières en terrasses. Chaque virage dévoilait un nouveau tableau : des étendues de verdure sculptées par la main de l’homme, entrecoupées de petits villages où les habitants portaient encore leurs costumes traditionnels. J’ai été accueilli par une famille Hmong pour un thé au gingembre, assis sur une terrasse en bois avec une vue plongeante sur la vallée. Le soir, la brume recouvrait lentement Sapa, ajoutant une touche mystique à cette région hors du temps.", likeNb: 2789, comNb: 210),
                         cardJB(photo: "Costa Rica", title: "🇨🇷 Alajuela", description: "Une porte d'entrée vers des merveilles naturelles, des volcans imposants aux forêts tropicales luxuriantes.", description_detail: "Ma journée a commencé aux pieds du volcan Poás, où l’odeur du soufre flottait dans l’air tandis que je contemplais le cratère fumant. Plus tard, je me suis aventuré dans une plantation de café où j’ai appris à reconnaître les arômes subtils d’un bon arabica. L’après-midi, j’ai plongé sous une cascade dans la jungle, l’eau fraîche contrastant avec la chaleur tropicale. En fin de journée, allongé dans des sources thermales naturelles sous un ciel étoilé, je me suis dit que le Costa Rica était vraiment un pays où la nature et l’aventure se mêlent à la perfection.", likeNb: 3674, comNb: 345),
                         cardJB(photo: "Osaka", title: "🏯 Osaka", description: "Une ville dynamique où la street food, l’énergie urbaine et la convivialité se rencontrent.", description_detail: "Surnommée « la cuisine du Japon », Osaka est célèbre pour sa gastronomie de rue et son atmosphère animée. Entre les néons de Dotonbori, le château d’Osaka et l’impressionnant quartier de Namba, la ville est un mélange parfait entre modernité et tradition. Réputée pour ses habitants chaleureux et son ambiance détendue, Osaka est une ville où l’on vient autant pour manger que pour s’imprégner de son énergie.", likeNb: 2674, comNb: 145),
                         cardJB(photo: "Kyoto", title: "🎎 Kyoto", description: "L’ancienne capitale impériale, entre temples millénaires, jardins zen et ruelles traditionnelles.", description_detail: "Kyoto est le cœur spirituel et culturel du Japon. Connue pour ses milliers de temples, ses sanctuaires shinto et ses ruelles pavées bordées de maisons en bois, elle offre un voyage hors du temps. Le quartier de Gion, avec ses geishas mystérieuses, et la bambouseraie d’Arashiyama sont des incontournables pour quiconque souhaite découvrir le Japon traditionnel.", likeNb: 1284, comNb: 76),
                         cardJB(photo: "Fukuoka", title: "🎏 Fukuoka", description: "Une ville portuaire moderne, réputée pour sa cuisine et son ambiance détendue.", description_detail: "Située sur l’île de Kyushu, Fukuoka est une ville en bord de mer connue pour ses plages, ses temples anciens et sa scène culinaire exceptionnelle. Moins frénétique que Tokyo ou Osaka, elle offre un cadre de vie agréable avec une nature omniprésente. C’est ici que l’on trouve les célèbres yatai (stands de rue), où l’on déguste un ramen Hakata authentique en plein air.", likeNb: 870, comNb: 98),
                         cardJB(photo: "France", title: "🥖 France", description: "Un pays aux mille visages, entre patrimoine historique, villages pittoresques et gastronomie inégalée..", description_detail: "La France est une destination aux multiples facettes, où chaque région dévoile un charme unique. Paris et ses monuments iconiques, la Provence et ses champs de lavande, la Côte d’Azur et ses eaux cristallines, ou encore la Bretagne et ses côtes sauvages… le pays offre un éventail de paysages et d’expériences incroyables. Sans oublier sa gastronomie légendaire, entre croissants, fromages et vins renommés dans le monde entier.", likeNb: 1675, comNb: 65),
                         cardJB(photo: "Espagne", title: "💃🏽 Espagne", description: "Une terre de passion, où se mêlent traditions vibrantes, paysages ensoleillés et gastronomie savoureuse.", description_detail: "L’Espagne, c’est la diversité à l’état pur. Des plages dorées d’Andalousie aux montagnes verdoyantes du Pays basque, en passant par les villes emblématiques comme Barcelone, Madrid ou Séville, chaque région possède une identité forte. Les tapas, le flamenco, les fêtes traditionnelles et l’héritage architectural de Gaudí ou des Maures font de l’Espagne une destination incontournable.", likeNb: 973, comNb: 29),
                         cardJB(photo: "Grèce", title: "🇬🇷 Grèce", description: "Un pays mythique, entre mer turquoise, vestiges antiques et villages blancs baignés de soleil.", description_detail: "La Grèce, berceau de la civilisation occidentale, fascine par son histoire millénaire et ses paysages enchanteurs. Entre Athènes et son Acropole, les îles des Cyclades aux maisons immaculées, la Crète sauvage et le Péloponnèse aux sites antiques incroyables, chaque voyage en Grèce est une plongée dans l’Histoire et la beauté naturelle.", likeNb: 529, comNb: 62)]

struct comment: Identifiable{
    var id = UUID()
    var text: String
    var image: String
    var username: String
    var nblike: Int
    var likeicon: String = "heart.fill"
    
}

var comments: [comment] = [comment(text: "Wow, ça donne trop envie d’y aller ! 😍", image: "Profil 3", username: "Sunny_St4r", nblike: 10),
                           comment(text: "Les photos sont magnifiques, quel endroit de rêve ! 😍", image: "Profil 5", username: "Sunny_St4r", nblike: 8),
                           comment(text: "Merci pour le partage, ça a l’air incroyable ! ✨", image: "Sunny", username: "Sunny_St4r", nblike: 3),
                           comment(text: "Hâte de lire ton prochain post, ça me fait voyager ! ✈️", image: "PP1", username: "Sunny_St4r", nblike: 20),
                           comment(text: "Je ne connaissais pas cet endroit, merci pour la découverte ! 🙌", image: "Profil 2", username: "Sunny_St4r", nblike: 5)]


class PostFavorite: ObservableObject{
    @Published var postfavoris: [cardJB]
    
    init(postfavoris: [cardJB] = []) {
        self.postfavoris = postfavoris
    }
}

var postfavoris = PostFavorite()
